steps:
  - label: "CUDA with julia {{matrix.julia}}"
    plugins:
      - JuliaCI/julia#v1:
          version: "{{matrix.julia}}"
      - JuliaCI/julia-test#v1: 
          test_args: "--quickfail"
    agents:
      queue: "juliagpu"
      cuda: "*"
    timeout_in_minutes: 60
    env:
      GROUP: "GPU"
      ADVANCEDVI_TEST_CUDA: "true"
    matrix:
      setup:
        julia:
           - "1.10"
