name: Mooncake Integration 
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:

jobs:
  Mooncake:
    uses: ./.github/workflows/AutoDiffIntegration.yml
    with:
      AD: Mooncake
